export const TARGET_FRATIO_MISMATCH_COEFFICIENT = 0.35;
export const DEFAULT_REFLECTIVITY_PER_MIRROR = 0.9;
export const DEFAULT_CORRECTOR_TRANSMISSION = 0.9;

export const DEFAULT_BACKFOCUS_MARGIN_MM = 50;
export const DEFAULT_TUBE_MARGIN_MM = 25;

export const NEWTONIAN_INTERCEPT_FRACTION = 0.25;

export const COMA_PROXY_COEFFICIENT = 1.0;
export const CASSEGRAIN_ABERRATION_PENALTY = 1.2;
export const SCT_ABERRATION_PENALTY = 1.4;
export const RC_ABERRATION_PENALTY = 0.8;

export const OBSTRUCTION_CONTRAST_COEFFICIENT = 0.15;

export const CASSEGRAIN_BAFFLE_FACTOR = 1.06;
export const RC_BAFFLE_FACTOR = 1.14;
export const SCT_BAFFLE_FACTOR = 1.22;

export const CASS_COMA_COEFF = 0.6;
export const CASS_ASTIG_COEFF = 0.35;
export const CASS_FIELD_CURV_COEFF = 0.35;
export const CASS_SPHERICAL_COEFF = 0.02;

export const RC_COMA_COEFF = 0.02;
export const RC_ASTIG_COEFF = 0.6;
export const RC_FIELD_CURV_COEFF = 0.35;
export const RC_SPHERICAL_COEFF = 0.02;

export const SCT_COMA_COEFF = 0.25;
export const SCT_ASTIG_COEFF = 0.35;
export const SCT_FIELD_CURV_COEFF = 0.55;
export const SCT_SPHERICAL_COEFF = 0.02;
